version: '2'
services:
  bot:
    image: yagotlima/scrum-master-bot:latest
    links:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/scrum-master-bot"
      HUBOT_SLACK_TOKEN_FILE: hubot-slack-token.env
      TZ: America/Sao_Paulo
  redis:
    image: "redis:4-alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: rancher-nfs
    onRemove: retain
